[package]
name = "learning-lm-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
safetensors = "0.5"
tokenizers = "0.21"
rand = "0.8"

num-traits = "0.2.19"
half = { version = "2.6", features = ["num-traits"] }
actix-web = "4.0"
actix-session = "0.5"
async-stream = "0.3"
bytes = "1"
actix-cors = "0.7"
futures = "0.3"
tokio = "1.44"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.16", features = ["v4"] }
cust = { version = "0.3" }
dashmap = "6.1"

[features]
default = ["gpu", "single"]
gpu = []
single = []